### ISSUE TITLE
Export API compatible with LoanScan.io needs

### ISSUE THREAD

**Issue by jgarzik** [vesperfi/issues#1]
Quoting from Discord,
> For platform listing on LoanScan.io, please use this interest rates format: https://gist.github.com/frostiq/4bfa6326c4647aecc8fd9c787ebbf1f9

> email api@loanscan.io for additional information.

**Comment by gabmontes** [comment]
@jgarzik the new route was deployed to production. Closing.

https://api.vesper.finance/loan-rates
