### ISSUE TITLE
Home page APY for vVSP isn't matching platform APY

### ISSUE THREAD

**Issue by Leonardiae** [vesperfi/issues#12]
https://vesper.finance/ shows:
![image](https://user-images.githubusercontent.com/49715529/115771947-d51cbf00-a3ae-11eb-8ef1-cb7bc51c6bbe.png)
https://app.vesper.finance/ shows:
![image](https://user-images.githubusercontent.com/49715529/115771969-de0d9080-a3ae-11eb-9f04-dcd468dc4520.png)

It seems not to be a browser cache issue because it also happens with everything fresh. Reproduced this in Chrome and Edge.

**Comment by gabmontes** [comment]
@Leonardiae thanks for reporting this. We expect to fix this inconsistency tomorrow morning.

**Comment by gabmontes** [comment]
Solved.

**Comment by Leonardiae** [comment]
Thanks @gabmontes !
