### ISSUE TITLE
My Stats: My Portfolio Balance: displays both vVSP and vETH in the same color

### ISSUE THREAD

**Issue by premie** [vesperfi/issues#13]
vVSP and vETH display colors in the portfolio tracker are too close in color

vVSP uses: rgb(65, 56, 172)
vETH user: rgb(67, 58, 173)

![unknown](https://user-images.githubusercontent.com/4683689/115807657-e90bf500-a39d-11eb-866b-23d19996bf05.png)

![Screen_Shot_2021-04-20_at_3 22 50_PM](https://user-images.githubusercontent.com/4683689/115807658-ea3d2200-a39d-11eb-92f3-015d8becf4c2.png)

**Comment by gabmontes** [comment]
@premie thanks for reporting that. Will take care of this!

**Comment by premie** [comment]
I see the new color. Still got great UX contrast, but at least it's not a big anymore.  Thanks.
