### ISSUE TITLE
Typo - Earning Rate explanation

### ISSUE THREAD

**Issue by premie** [vesperfi/issues#16]
<img width="1183" alt="Typo" src="https://user-images.githubusercontent.com/4683689/116478856-99ad4500-a833-11eb-8a46-1bdeacc984ad.png">

"The "spot" earning rate is calculated as last 24-hours performance annualized and compounded, while "average" reflects the past 30-days annualived and compounded."
There's a typo there - 'annualived'

**Comment by jgarzik** [comment]
@premie need more info: is this the app or the website? which page in the browser bar shows?

**Comment by premie** [comment]
In the app https://app.vesper.finance/veth when you hover over the question mark next to "Earning Rate"

**Comment by gabmontes** [comment]
@premie thanks for reporting. Fixing it ASAP.

**Comment by premie** [comment]
awesome!
