### ISSUE TITLE
Unable to Access Deposit

### ISSUE THREAD

**Issue by zhhuffman** [vesperfi/issues#2]
From User on Discord:

* Wallet holds enough ETH/WETH
* Neither main nor development website recognizes balance, shows 0
* Deposit area is grayed out, not possible to manually enter an amount
* website refresh did not help

User reports being on WalletConnect and Chrome. Their balance is fetched by other websites (Aave) and the Vesper site indicates that they are properly connected. I was unable to replicate this issue myself (using MM, not walletconnect). I did confirm that his address was funded (holds some amount of ETH and WETH).

**Comment by gabmontes** [comment]
I was able to reproduce a similar scenario using Safari/iOS and Trust Wallet. Need further research.

**Comment by gabmontes** [comment]
@zhhuffman we just deployed a fix to prod that solves this problem.

Please verify and close the issue or comment back.
