### ISSUE TITLE
$ calculations on UI are not being generated correctly. For both pool deposits and user deposits

### ISSUE THREAD

**Issue by HitachiCloud** [vesperfi/issues#23]
$ calculations on vesper.finance UI and orbit.vesper.finance are not being generated correctly. For both pool deposits and user deposits
See discord thread https://discord.com/channels/763794227116507156/763794227116507159/914305909356908594

I used USDT example but other users with FRAX deposits into orbit are also seeing the same behavior. UI is not using the correct oracle feed for $ conversion.

**Comment by gabmontes** [comment]
@HitachiCloud the displayed dollar amounts are correct:

Pool total supply = 5,064,629 vUSDT
Pool token value = 1.019478 USDT/vUSDT
Pool deposits = Pool total supply x Pool token value = 5,163,278 USDT
USDT price = 0.995127 USD/USDT
Value locked = Pool deposits x USDT price = 5,138,118 USD

Disregard any rounding difference, of course.

**Comment by xatilla** [comment]
Gab - The value of USDT is not 0.995127... its 1.0008.. you are missing a digit of **resolution.**.  Look at chainlink price feed https://data.chain.link/ethereum/mainnet/stablecoins/usdt-usd, which is 1.0007-1.0009, so where  is UI getting that USDT value.. Also, I took two screenshots this morning 5,127,268 and 5,146,287..  If pool deposits are 5,163,278 , the USD value is 5163278*1.0008 which is 5,167,150...

**Comment by xatilla** [comment]
Also, note users who deposit into FRAX on orbit (message raised on telegram) are also seeing a discrepancy in the conversion of FRAX to $USD.. something suspect with source of data for $ conversions.... are we not using oracle ?

**Comment by xatilla** [comment]
reopened as issue 24 as I see this case was closed by dev https://github.com/vesperfi/issues/issues/24
